### PR TITLE
Migrate docs #938

### PR DESCRIPTION
**Pull request by duffney**
Migrating the docs and structure from https://github.com/deislabs/ratify/tree/main/docs to the ratify-web repo.

Note: I only added the necessary Docusaurus metadata to the necessary docs to algin the table of content and to add relevant heading information. Most of the docs are not mdx files and default to their H1 title as the name and use alphabetical sorting. My reasoning was that within the refactoring that metadata is likely to change.

### CODE REVIEW

**Comment by duffney** [comment]
I'm looking into the build failures. :)

**Comment by duffney** [comment]
> Thank you @duffney! You can find the [error logs](https://app.netlify.com/sites/ratify-dev/deploys/64fb62fa55739b0008a97775) to troubleshoot the build error. It looks like there are some broken links in some .md files.
> 
> BTW, the [README](https://github.com/deislabs/ratify-web) provides a guideline to build and test the website locally. Make sure you can successfully build and preview the website in your local.

Thanks for the advice @FeynmanZhou :) I was able to get the build working with no bad link errors. For all references to the ratify repo I just pointed the docs to the main branch of Ratify.

**Comment by FeynmanZhou** [comment]
@duffney Thanks for your quick action! Note that we will remove the original Ratify docs from the Ratify code repo after the migration is completed. Raising a follow-up PR to address the links sounds good to me. Please make sure to use the relative links for reference docs. Thanks!

**Comment by luisdlp** [comment]
LGTM, thanks for doing this.

**Review by luisdlp — APPROVED** [review]

**Pull request merged**
